### ISSUE TITLE
Depreciation warning popup and message about st.experimental_dialog since streamlit 1.37.0

### ISSUE THREAD

**Issue by bulletmark** [444B/streamlit-analytics2#111]
Since streamlit version 1.37.0, we get a display popup at app start and a message on stdout saying:
```
2024-08-06 15:46:39.661 Please replace `st.experimental_dialog` with `st.dialog`.

`st.experimental_dialog` will be removed after 2025-01-01.
```

See streamlit [1.37.0 release notes](https://github.com/streamlit/streamlit/releases/tag/1.37.0).

`src/streamlit_analytics2/display.py` line 11 needs update. Was going to add a PR but wasn't sure if best to add a runtime check on streamlit version (for backwards compatibility), or just up the minimum version in `pyproject.toml`.

This is using `streamlit_analytics2` version 0.8.1.

**Comment by 444B** [comment]
@bulletmark thank you for raising this! 
We will opt to use the GA function and bump the version 
A runtime check for backwards compatibility is a good idea but only if it needed and I would rather not build up on tech debt by supporting deprecated functions if there is a GA version

Feel free to make the PR

If you prepend the branch name with "test/" it will generate a test package on test.pypi that can be checked before pushing out to the main release on merge
