### ISSUE TITLE
[FEATURE] Track unique users

### ISSUE THREAD

**Issue by ArthurG29** [444B/streamlit-analytics2#121]
My company has asked whether the observed activity on the platform is driven by a small group of users or a larger number of unique users. Hence I believe it would be useful to track the number of unique users interacting with the application.

This could be implemented either as an additional graph or by adding an option to the existing usage graph. Ideally, there would also be a filter option to segment activity by individual users.

To achieve this, I think it might be necessary to leverage cookies or similar mechanisms for user identification.

**Comment by 444B** [comment]
Hi Arthur
Sounds good!
Take a look at the following for how this may be achieved:
 https://github.com/444B/streamlit-analytics2/discussions/120 

If you can submit a PR with an integration I will happily review and accept it
