### ISSUE TITLE
Option to load firestore key from dict 

### ISSUE THREAD

**Issue by 444B** [444B/streamlit-analytics2#21]
Original issue by alizahidraja on 2023-02-28 20:52:22+00:00

I am trying to deploy an app & I do not want to publicly show my firebase key

For this I use `st.secrets` to make a dict object, but there is no option to pass it to the track function

**Comment by 444B** [comment]
Comment by nathanjones4323 on 2023-03-08 19:47:59+00:00

@alizahidraja [This PR I just created would resolve your issue](https://github.com/jrieke/streamlit-analytics/pull/30).

If you want to use this or see this merged, give it a 👍

**Comment by 444B** [comment]
Comment by alizahidraja on 2023-03-08 19:53:19+00:00

Thankyou so much!

**Comment by 444B** [comment]
@alizahidraja  @nathanhones is this still relevant?

**Comment by hansipie** [comment]
Hello
... for me it is :)
