### ISSUE TITLE
Create full path for tracking file

### ISSUE THREAD

**Issue by 444B** [444B/streamlit-analytics2#23]
Original issue by Nickelza on 2023-02-06 00:51:59+00:00

When given a file.json to store data, it'd be nice if the path to the file is created if it doesn't exist

**Comment by 444B** [comment]
@Nickelza is this still relevant?

**Comment by Nickelza** [comment]
> @Nickelza is this still relevant?

Yeah it is, thanks a bunch

**Comment by 444B** [comment]
Thanks! Will take a look into it

**Comment by 444B** [comment]
@Nickelza This now works in the latest version 0.5.3 of streanlit-analytics2
A full path will be created if one does not exist
Check out the migration guide in the wiki of this repo if you have any questions
:)
