### ISSUE TITLE
support for multipage - fork / wrap st.title?

### ISSUE THREAD

**Issue by 444B** [444B/streamlit-analytics2#30]
Original issue by fredzannarbor on 2022-08-12 06:15:42+00:00

Hi,

I want to have some analytics for my multipage app. I forked @franasol's fork and took a look. It seems as if the way to proceed is to create wrapper functions for the page filename and st.title, then feed the results into a new object that is compatible with the other counting objects. Is that more or less correct? Any gotchas?

**Comment by 444B** [comment]
Comment by ianleifer on 2023-12-21 15:19:28+00:00

Hi, just curious if there was any progress made on this.

**Comment by 444B** [comment]
@fredzannarbor  @ianleifer  is this still relevant?

**Comment by fredzannarbor** [comment]
I don't think so
---
Fred Zimmerman, Publisher
Nimble Books LLC
The AI Lab for Book-Lovers <http://NimbleBooks.com>
