### ISSUE TITLE
[BUG] Logging basicConfig may be imported and overwriting logging for user modules

### ISSUE THREAD

**Issue by 444B** [444B/streamlit-analytics2#78]
**Describe the bug**
- While using SA2 for a custom project, I realized there was logging taking place into standard output when this was not intended
- This was being attributed to SA2: 
- ```streamlit-analytics2: INFO: HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"```
- However I can rule out without a single doubt that this was not intended behavior 
- As a result of this knowledge, I can not allow such unintended behavior for the other users of SA2 (currently around 350 downloads a month)

**Expected behavior**
- Logging should only be invoked if "verbose" is passed as an argument to track() or an alternative function

**Software Vesions**
Please fill in the relevant field:
- streamlit_analytics2 : 0.7.2
- streamlit : 1.33.0
- Python3 : 3.10.12

**Comment by brianshin22** [comment]
Hi, thanks for the work on this project. Any updates on this by any chance? I noticed my custom logging stopped working after integrating SA2 as well.

**Comment by 444B** [comment]
Hey Brian!
Thanks for the reminder on that
I will look into disabling the custom logging from SA2 until a more suitable solution is found
